server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: provider
          uri: lb://sentinel-provider
          predicates:
            - Path=/provider/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
        - id: consumer
          uri: lb://sentinel-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        flow:
          nacos:
            ### nacos连接地址
            server-addr: 127.0.0.1:8848
            ## nacos连接的分组
            group-id: SENTINEL_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: gateway-flow-rules
            ###  读取培训文件类型为json
            data-type: json
            username: nacos
            password: nacos
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
feign:
  sentinel:
    enabled: true