server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
#      routes:
#        - id: provider
#          uri: lb://sentinel-provider
#          predicates:
#            - Path=/sentinel-provider/**
#          filters:
#            - StripPrefix=1
#        - id: consumer
#          uri: lb://sentinel-consumer
#          predicates:
#            - Path=/sentinel-consumer/**
#          filters:
#            - StripPrefix=1
    sentinel:
      scg:
        order: -100
        fallback:
          mode: response
          response-status: 455
          response-body: 系统繁忙
      transport:
        dashboard: 127.0.0.1:8080
  main:
    allow-bean-definition-overriding: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1