server:
  port: 8081
spring:
  application:
    name: sentinel-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 10.10.11.106:48002
      datasource:
        flow:
          nacos:
            ### nacos连接地址
            server-addr: 10.10.11.101:8849,10.10.11.102:8849,10.10.11.110:8849
            namespace: d2eb05e6-c551-48ad-b66a-5fa7a5473c53
            ## nacos连接的分组
            group-id: SENTINEL_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: sentinel-consumer-flow-rules
            ###  读取培训文件类型为json
            data-type: json
            username: nacos
            password: nacos
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1