server:
  port: 8081
spring:
  application:
    name: sentinel-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1