server:
  port: 8083
spring:
  application:
    name: sentinel-provider
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 10.10.11.106:48002
      datasource:
        flow:
          nacos:
            ### nacos连接地址
            server-addr: 10.10.11.101:8849,10.10.11.102:8849,10.10.11.110:8849
            namespace: d2eb05e6-c551-48ad-b66a-5fa7a5473c53
            ## nacos连接的分组
            group-id: SENTINEL_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: sentinel-provider-flow-rules
            ###  读取培训文件类型为json
            data-type: json
            username: nacos
            password: nacos
        degrade:
          nacos:
            ### nacos连接地址
            server-addr: 127.0.0.1:8848
            ## nacos连接的分组
            group-id: SENTINEL_GROUP
            ###路由存储规则
            rule-type: degrade
            ### 读取配置文件的 data-id
            data-id: sentinel-provider-degrade-rules
            ###  读取培训文件类型为json
            data-type: json
            username: nacos
            password: nacos