server:
  port: 8083
spring:
  application:
    name: sentinel-provider
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080